title: Jonathan's Math 485 Website

theme: minima
---
title:
layout: default
---

Hello!

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ page.title }} - {{site.title}}</title>
</head>
<body>

  {{ content }}

</body>
</html>
